spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  profiles:
      include: oauth

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true # hibernate가 초기화되기 전 user-data.sql 실행하는 것을 방지
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/culturestamp-local?characterEncoding=utf8
    username: root
    password: 1234

app :
  jwtSecret : 7688ldhskljdlkjsakdapskfjdldldlpdkkkdd;;;kdkddld;;ssldld;j228092889
  googleClientId : 398701196846-1n8sr22rc55etti1cedf9qvnaovpfb4q.apps.googleusercontent.com

---
# test 환경
# spring:
#   config:
#     activate:
#       on-profile: test
#   datasource:
#     url: jdbc:h2:mem:culture;DB_CLOSE_ON_EXIT=FALSE  # db 주소 고정
#   #  sql:
#   #    init:
#   #      data-locations: classpath:data-for-h2.sql # 시작할때 실행시킬 script
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     defer-datasource-initialization: true # hibernate가 초기화되기 전 user-data.sql 실행하는 것을 방지
#     #  show-sql: true
#     hibernate:
#       format_sql: true
#       ddl-auto: create-drop
# logging:
#   level:
#     root: DEBUG
#     org:
#       springframework:
#         security: DEBUG
